Sprint 4
IlyaKotovskiy/kot-messenger pull request #6
Opened 2024-11-16 14:20 UTC by IlyaKotovskiy

2024-11-16 18:30 UTC, IlyaKotovskiy commented
Удаление пользователя из чата, происходит по клику на пользователя

2024-11-16 21:48 UTC, aromanovnik requested changes
Добрый день, Илья!

Работа выполнена очень хорошо: все тесты написаны, аудит пакетов не выявил ни одной уязвимости. Код выглядит чисто и аккуратно.

Тем не менее, есть несколько замечаний, включая моменты из предыдущих спринтов, так как это финальный этап, и приложение должно работать корректно. Более подробное описание всех замечаний дано в комментариях к коду.

Что нужно исправить:
* `Precommit` должен включать не только тесты, но и проверку кода линтерами. 
* По чеклисту `Stylelint` должен быть настроен.
* При переключении между чатами в приложении должны загружаться сообщения, соответствующие активному чату. Сейчас этого не происходит. https://disk.yandex.ru/i/w4wUhBnTVPVylw
* Если пользователь уже авторизован, при попытке доступа к страницам “Вход” и “Регистрация” он должен автоматически перенаправляться на страницу чатов.
* Валидация должна происходить не только при изменении значения поля, но и на событие `blur` (когда поле теряет фокус). https://disk.yandex.ru/i/FUJkFNe5Vct3Dg

Что можно улучшить:
* Цвета лучше вынести в CSS-переменные, чтобы улучшить читаемость и поддержку кода. Это позволяет мгновенно понять назначение цвета, избежать дублирования, а также облегчить изменения — достаточно подкорректировать цвет в одном месте, что повышает гибкость и масштабируемость стилей.
* `ESLint` установлен, но не добавлен в блок scripts. Рекомендую добавить команду в scripts, например `"eslint": "eslint \"src/**/*.[jt]s\""`.
* Лучше использовать .equal(true) вместо .be.true, так как использование метода .equal() делает намерение теста более очевидным и понятным.

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-11-16 21:48 UTC, aromanovnik commented on package.json
> +    "test": "mocha --no-warnings --exit"
**Надо исправить**: По чеклисту `Stylelint` должен быть настроен. Это необходимо для автоматической проверки стилей на соответствие стандартам и устранения возможных ошибок в CSS-коде.

<img width="769" alt="Снимок экрана 2024-11-17 в 00 22 02" src="https://github.com/user-attachments/assets/3040a46a-7390-4aca-9cc6-8703d0bdadae">

2024-11-16 21:48 UTC, aromanovnik commented on .husky/pre-commit
> +npm test
**Надо исправить**: `Precommit` должен включать не только тесты, но и проверку кода линтерами. Это помогает поддерживать кодовую базу в соответствии с установленными стандартами качества. Рекомендуется создать команду `npm run pre-commit`, которая объединяет запуск тестов и линтеров, чтобы автоматизировать этот процесс и избежать пропуска проверки.

<img width="1143" alt="Снимок экрана 2024-11-17 в 00 10 07" src="https://github.com/user-attachments/assets/3182819d-70b0-41c6-90d8-088ae39b34db">

2024-11-16 22:15 UTC, IlyaKotovskiy commented on .husky/pre-commit
> +npm test
По поводу сообщений в чате. Там все отлично работает, как локально, так и на netlify. Посмотрите еще раз, пожалуйста. Док-ва: https://imgur.com/a/pf89rUv.

2024-11-16 22:15 UTC, IlyaKotovskiy commented
По поводу сообщений в чате. Там все отлично работает, как локально, так и на netlify. Посмотрите еще раз, пожалуйста. Док-ва: https://imgur.com/a/pf89rUv.

2024-11-17 01:01 UTC, IlyaKotovskiy commented
1) Валидация теперь и на событие blur
2) Настроен Stylelint
3) Переделан Pre-Commit, теперь при пре-комите срабатывают тесты и линтер.
4) Если пользователь уже авторизован, то он больше никак не попадет на страницу входа или регистрации.
По поводу сообщений в чате. Там все отлично работает, как локально, так и на netlify. Посмотрите еще раз, пожалуйста. Док-ва: https://imgur.com/a/pf89rUv.

2024-11-17 12:14 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. 

Что можно улучшить:
* В проекте используется **45 раз тип any**, что многовато для такого небольшого проекта. Использование `any` плохо тем, что оно отключает проверку типов TypeScript, фактически превращая ваш код в обычный JavaScript. Это снижает надежность типизации, затрудняет отладку и увеличивает вероятность ошибок. Лучше заменить any на более точные типы или использовать `unknown`, который требует явного приведения типов перед использованием. Это улучшит читаемость, предсказуемость и качество кода.
* Сообщения не обновляются при переключении на **пустой чат** (в котором еще нет сообщений). Проблема связана с условием `store.getState().messages.length` в файле `HOC.ts`. Такое условие не учитывает ситуации, когда массив сообщений пуст, и пропускает обновление данных. Рекомендуется пересмотреть это условие, например, проверить существование сообщений не по длине массива, а на основании ID активного чата или другого критерия. Это позволит избежать пропуска обновлений.

Желаю успехов в дальнейшей учебе!

2024-11-17 12:27 UTC, merged